# https://leetcode.com/problems/find-the-difference/
# 389. Find the Difference

# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if len(s) == 0:
            return t
            
        i = 0
        while i < len(s):
            if s[i] in t:
                t = t.replace(s[i], "", 1)
            i += 1

        return t